spring:
  datasource:
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/TrainSys?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true

mybatis:
  mapper-locations: classpath:\config\mapping\*.xml
  type-aliases-package: classpath:com\caopan\TrainSys\model
